### PR TITLE
Time Component Finished - minus database and styling

### PR DESCRIPTION
**Pull request by keplerridge**
…t should be fairly easy once we have shared all of the DB info and have it hosted online. It also needs to be styled so once we have a styling guide we can get started on that. I added it to the router so that it is easy to see from the home page. If you open the web browser developer tools we can see that when you click start, stop, save, and delete that it is working.

### CODE REVIEW

**Review by keatonflake — DISMISSED** [review]
Looks great!

**Review by funnyman569 — APPROVED** [review]
Looks Good

**Review by funnyman569 — APPROVED** [review]
Looks good

**Review by keatonflake — APPROVED** [review]
Good Job Kepler

**Pull request merged**
