### PR TITLE
Timer feature component

### PR DESCRIPTION
**Pull request by keplerridge**
I adjusted this so that it is saving the latitude and longitude instead of a string formatted address.

### CODE REVIEW

**Review by funnyman569 — APPROVED** [review]
Well need to resolve merge conflicts

**Review by funnyman569 — APPROVED** [review]
Looks Good!

**Review by funnyman569 — APPROVED** [review]
gg

**Review by scjk25 — APPROVED** [review]
changes look good I am going to approve it.

**Pull request merged**
