### PR TITLE
Acitivity card component with testing included. I added a backend fol…

### PR DESCRIPTION
**Pull request by funnyman569**
…der to handle the importing from a postgres database. It passed the vitest but I haven't been able to actually open it on a webpage. But I know at least works! 

(a few changes were made to some parent files like package.json in speeddemon repo as I was doing package configuration but they are incidental changes I believe)

### CODE REVIEW

**Review by keatonflake — APPROVED** [review]
Great job!

**Review by keplerridge — DISMISSED** [review]
Looks good, thanks!

**Review by keplerridge — APPROVED** [review]
Good job, I handled  a couple more merge conflicts that arose.

**Review by keatonflake — APPROVED** [review]
Looks great

**Pull request merged**
